permalink: /:year/:month/:day/:title/
title: YEGRB
subtitle: "Edmonton's Ruby Meetup"
author_name: YEGRB
webmaster_email: alan@yegrb.com
homepage_url: http://yegrb.com
atom_url: /atom.xml
rss_url: /rss.xml

plugins: [jekyll-paginate]
# gems:
#   - jekyll-paginate
paginate: 3

exclude:
  [
    "README",
    "Rakefile",
    "Gemfile",
    "Gemfile.lock",
    "build",
    "bin",
    "resources",
    ".gitignore",
  ]

safe: true
lsi: false
highlighter: rouge

timezone: America/Edmonton
encoding: UTF-8

markdown: kramdown
